LANG = {
    'English': {
        'title': 'Water Issue Tracker - Civic System',
        'menu': 'Menu',
        'dashboard': 'Dashboard',
        'report': 'Report Issue',
        'view': 'View Complaints',
        'admin': 'Admin Panel',
        'total': 'Total Complaints',
        'pending': 'Pending',
        'resolved': 'Resolved',
        'report_title': 'Citizen AI Complaint System',
        'citizen_ai': 'Citizen AI',
        'admin_dashboard': 'Admin Dashboard',
        'name': 'Name',
        'phone': 'Phone',
        'problem_explain': 'Explain your water problem',
        'upload_evidence': 'Upload Evidence',
        'analyze_complaint': '🤖 Analyze Complaint',
        'submit': 'Submit Complaint',
        'success': 'Complaint Submitted',
        'fill_required': 'Fill required fields',
        'invalid_phone': 'Invalid phone number',
        'view_details': 'View Details',
        'citizen_proof': 'Citizen Proof',
        'resolution_details': 'Resolution Details',
        'resolution_proof': 'Upload Resolution Proof',
        'admin_password': 'Admin Password',
        'admin_success': 'Complaint updated successfully',
        'status': 'Status',
        'complaint_index': 'Complaint Index',
        'selected_issue': 'Selected Issue:',
        'current_status': 'Current Status:',
        'update': 'Update Complaint',
        'wrong': 'Wrong Password',
        'ai_mode': 'AI Mode',
        'local_ai': 'Project Groq AI',
        'byok_ai': 'BYOK - Bring Your Own Key',
        'api_key': 'Enter Groq API Key',
        'issue_type': 'Issue Type',
        'location': 'Location',
        'priority': 'Priority',
        'description': 'Description',
        'low': 'Low',
        'medium': 'Medium',
        'high': 'High',
        'emergency': 'Emergency',
        'ai_result': 'AI Analysis Result',
        'ai_processing': 'AI is analyzing the complaint...',
        'ai_complete': 'AI analysis complete.',
        'ai_solution': 'AI Suggested Solution',
        'ai_suggest_solution': 'AI Suggest Solution',
        'ai_status': 'AI Status',
        'progress': 'Progress',
        'estimated_completion': 'Estimated Completion',
        'ai_updates': 'AI Updates',
        'admin_solution': 'Admin Solution',
        'final_ai_report': 'Final AI Report',
        'fill_api_key': 'Enter a Groq API key for BYOK mode',
        'ai_status_initial': 'AI complaint triage in progress',
        'ai_updates_initial': 'AI analysis started',
        'help': 'Help Desk',
        'help_title': 'Help Desk and AI Support',
        'help_description': 'Ask for help about complaint submission, AI analysis, or the tracker workflow.',
        'support_contact': 'For urgent issues, contact your local water authority.',
        'help_chat_prompt': 'Type your question here...',
        'help_submit': 'Submit Help Request',
        'help_response': 'Help Desk Response',
        'possible_cause': 'Possible Cause',
        'repair_steps': 'Repair Steps',
        'department': 'Department',
        'urgency': 'Estimated Urgency',
        'no_complaints': 'No complaints available',
    },
    'Telugu': {
        'title': 'నీటి సమస్యల ట్రాకర్ - పౌర వ్యవస్థ',
        'menu': 'మెనూ',
        'dashboard': 'డాష్‌బోర్డ్',
        'report': 'సమస్యను నివేదించండి',
        'view': 'ఫిర్యాదులు చూడండి',
        'admin': 'అడ్మిన్ ప్యానెల్',
        'total': 'మొత్తం ఫిర్యాదులు',
        'pending': 'పెండింగ్',
        'resolved': 'పరిష్కరించబడినవి',
        'report_title': 'పౌర AI ఫిర్యాదు వ్యవస్థ',
        'citizen_ai': 'పౌర AI',
        'admin_dashboard': 'అడ్మిన్ డాష్‌బోర్డ్',
        'name': 'పేరు',
        'phone': 'ఫోన్ నంబర్',
        'problem_explain': 'మీ నీటి సమస్యను వివరించండి',
        'upload_evidence': 'ఆధారాలను అప్‌లోడ్ చేయండి',
        'analyze_complaint': '🤖 ఫిర్యాదును విశ్లేషించండి',
        'submit': 'ఫిర్యాదు సమర్పించండి',
        'success': 'ఫిర్యాదు సమర్పించబడింది',
        'fill_required': 'అవసరమైన వివరాలు నమోదు చేయండి',
        'invalid_phone': 'చెల్లని ఫోన్ నంబర్',
        'view_details': 'వివరాలు చూడండి',
        'citizen_proof': 'పౌర ఆధారాలు',
        'resolution_details': 'పరిష్కార వివరాలు',
        'resolution_proof': 'పరిష్కార ఆధారాలను అప్‌లోడ్ చేయండి',
        'admin_password': 'అడ్మిన్ పాస్‌వర్డ్',
        'admin_success': 'ఫిర్యాదు విజయవంతంగా నవీకరించబడింది',
        'status': 'స్థితి',
        'complaint_index': 'ఫిర్యాదు సూచిక',
        'selected_issue': 'ఎంచుకున్న సమస్య:',
        'current_status': 'ప్రస్తుత స్థితి:',
        'update': 'ఫిర్యాదును నవీకరించండి',
        'wrong': 'తప్పు పాస్‌వర్డ్',
        'ai_mode': 'AI విధానం',
        'local_ai': 'ప్రాజెక్ట్ Groq AI',
        'byok_ai': 'BYOK - మీ స్వంత కీ',
        'api_key': 'Groq API కీ నమోదు చేయండి',
        'issue_type': 'సమస్య రకం',
        'location': 'ప్రాంతం',
        'priority': 'ప్రాధాన్యత',
        'description': 'వివరణ',
        'low': 'తక్కువ',
        'medium': 'మధ్యస్థ',
        'high': 'అధిక',
        'emergency': 'అత్యవసరం',
        'ai_result': 'AI విశ్లేషణ ఫలితం',
        'ai_processing': 'AI ఫిర్యాదును విశ్లేషిస్తోంది...',
        'ai_complete': 'AI విశ్లేషణ పూర్తయింది.',
        'ai_solution': 'AI సూచించిన పరిష్కారం',
        'ai_suggest_solution': 'AI పరిష్కారం సూచించు',
        'ai_status': 'AI స్థితి',
        'progress': 'ప్రగతి',
        'estimated_completion': 'అంచనా పూర్తి సమయం',
        'ai_updates': 'AI నవీకరణలు',
        'admin_solution': 'అడ్మిన్ పరిష్కారం',
        'final_ai_report': 'చివరి AI నివేదిక',
        'fill_api_key': 'BYOK విధానానికి Groq API కీ నమోదు చేయండి',
        'ai_status_initial': 'AI ఫిర్యాదు పరిశీలన కొనసాగుతోంది',
        'ai_updates_initial': 'AI విశ్లేషణ ప్రారంభమైంది',
        'help': 'సహాయ కేంద్రం',
        'help_title': 'సహాయ కేంద్రం మరియు AI మద్దతు',
        'help_description': 'ఫిర్యాదు సమర్పణ, AI విశ్లేషణ లేదా ట్రాకర్ విధానం గురించి సహాయం అడగండి.',
        'support_contact': 'అత్యవసర సమస్యల కోసం మీ స్థానిక నీటి అధికారులను సంప్రదించండి.',
        'help_chat_prompt': 'మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...',
        'help_submit': 'సహాయ అభ్యర్థన పంపండి',
        'help_response': 'సహాయ కేంద్ర స్పందన',
        'possible_cause': 'సంభావ్య కారణం',
        'repair_steps': 'మరమ్మత్తు దశలు',
        'department': 'విభాగం',
        'urgency': 'అంచనా అత్యవసరత',
        'no_complaints': 'ఫిర్యాదులు లేవు',
    },
    'Hindi': {
        'title': 'जल समस्या ट्रैकर - नागरिक प्रणाली',
        'menu': 'मेनू',
        'dashboard': 'डैशबोर्ड',
        'report': 'समस्या दर्ज करें',
        'view': 'शिकायतें देखें',
        'admin': 'एडमिन पैनल',
        'total': 'कुल शिकायतें',
        'pending': 'लंबित',
        'resolved': 'हल की गईं',
        'report_title': 'नागरिक AI शिकायत प्रणाली',
        'citizen_ai': 'नागरिक AI',
        'admin_dashboard': 'एडमिन डैशबोर्ड',
        'name': 'नाम',
        'phone': 'फोन नंबर',
        'problem_explain': 'अपनी पानी की समस्या बताएं',
        'upload_evidence': 'सबूत अपलोड करें',
        'analyze_complaint': '🤖 शिकायत का विश्लेषण करें',
        'submit': 'शिकायत जमा करें',
        'success': 'शिकायत जमा हो गई',
        'fill_required': 'आवश्यक विवरण भरें',
        'invalid_phone': 'अमान्य फोन नंबर',
        'view_details': 'विवरण देखें',
        'citizen_proof': 'नागरिक प्रमाण',
        'resolution_details': 'समाधान विवरण',
        'resolution_proof': 'समाधान प्रमाण अपलोड करें',
        'admin_password': 'एडमिन पासवर्ड',
        'admin_success': 'शिकायत सफलतापूर्वक अपडेट हुई',
        'status': 'स्थिति',
        'complaint_index': 'शिकायत सूचकांक',
        'selected_issue': 'चयनित समस्या:',
        'current_status': 'वर्तमान स्थिति:',
        'update': 'शिकायत अपडेट करें',
        'wrong': 'गलत पासवर्ड',
        'ai_mode': 'AI मोड',
        'local_ai': 'प्रोजेक्ट Groq AI',
        'byok_ai': 'BYOK - अपनी कुंजी',
        'api_key': 'Groq API कुंजी दर्ज करें',
        'issue_type': 'समस्या प्रकार',
        'location': 'स्थान',
        'priority': 'प्राथमिकता',
        'description': 'विवरण',
        'low': 'कम',
        'medium': 'मध्यम',
        'high': 'उच्च',
        'emergency': 'आपातकालीन',
        'ai_result': 'AI विश्लेषण परिणाम',
        'ai_processing': 'AI शिकायत का विश्लेषण कर रहा है...',
        'ai_complete': 'AI विश्लेषण पूरा हुआ.',
        'ai_solution': 'AI सुझाया समाधान',
        'ai_suggest_solution': 'AI समाधान सुझाएं',
        'ai_status': 'AI स्थिति',
        'progress': 'प्रगति',
        'estimated_completion': 'अनुमानित पूर्णता',
        'ai_updates': 'AI अपडेट',
        'admin_solution': 'एडमिन समाधान',
        'final_ai_report': 'अंतिम AI रिपोर्ट',
        'fill_api_key': 'BYOK मोड के लिए Groq API कुंजी दर्ज करें',
        'ai_status_initial': 'AI शिकायत जांच जारी है',
        'ai_updates_initial': 'AI विश्लेषण शुरू हुआ',
        'help': 'हेल्प डेस्क',
        'help_title': 'हेल्प डेस्क और AI सहायता',
        'help_description': 'शिकायत जमा करने, AI विश्लेषण या ट्रैकर प्रक्रिया के बारे में मदद पूछें.',
        'support_contact': 'तत्काल समस्याओं के लिए अपने स्थानीय जल प्राधिकरण से संपर्क करें.',
        'help_chat_prompt': 'अपना प्रश्न यहां लिखें...',
        'help_submit': 'सहायता अनुरोध जमा करें',
        'help_response': 'हेल्प डेस्क उत्तर',
        'possible_cause': 'संभावित कारण',
        'repair_steps': 'मरम्मत चरण',
        'department': 'विभाग',
        'urgency': 'अनुमानित तात्कालिकता',
        'no_complaints': 'कोई शिकायत उपलब्ध नहीं',
    },
}
